# app/seeds/createSeeds.py

from app.models import User
from random import randint, choice

seedNames = \
[
# Adds a demo user, you can add other users here
'Demo Lition',
'Alex Thoo',
'Andrei Vorobev',
'Ann Mulling',
'Brian Kiesel',
'Cory Campbell',
'Hector Crespo',
'Khuong Nguyen',
'Malcolm Caleb',
'Mason Austin',
'Matt Kim',
'Mugil Choi',
'Nina Bell',
'Peang Ngo',
'Peter Dinh',
'Quinn Bush',
'Rae Tsui',
'Roderick Johnson',
'Ryan Fournier',
'Sophia Tsau',
'Sophie Yang',
'Viviane Le',
'Zohaib Rajan',
]
seedEmails = [n.split(' ')[0].lower() + '@aa.io' for n in seedNames]

users = []

# Although we query, no explicit commit();
# we assume seeding will handle that for us
def getUsers():
    global users
    if len(users) == 0:
        users = User.query.filter(User.email.in_(seedEmails)).all()
    return users

seedUserIds = []

def getIds():
    global seedUserIds
    if len(seedUserIds) == 0:
        users = getUsers()
        seedUserIds = [u.id for u in users]
        print("emails:", seedEmails)
        print("Seed ids", seedUserIds)
    return seedUserIds

teamNames = [
    "Agile Developers",
    "Agile Minds",
    "Agile Systems",
    "Analysis Avengers",
    "Business Buffalos",
    "Business Bulldogs",
    "Business Pros",
    "Business Sharks",
    "Business as Usual",
    "Code Crusaders",
    "Code Warriors",
    "Coding Cobras",
    "Creative Champions",
    "Customer Care Crusaders",
    "Design Dreamers",
    "Digital Destroyers",
    "Digital Divas",
    "Digital Dream Team",
    "Digital Dreamers",
    "Digital Dynamos",
    "Digital Eagles",
    "Dynamic Developers",
    "Edison’s Innovators",
    "Efficiency Experts",
    "Finance Wizards",
    "Galileo Group",
    "Growth Gurus",
    "Growth Hackers",
    "HR Heroes",
    "Innovation Inc.",
    "Innovation Incubators",
    "Innovation Initiative",
    "Innovation Inspiration",
    "Innovation Instigators",
    "Innovation Invasion",
    "Innovative Inventors",
    "Marketing Maestros",
    "Marketing Magicians",
    "Marketing Maniacs",
    "Marketing Marvels",
    "Marketing Masterminds",
    "Marketing Masters",
    "Marketing Mavericks",
    "Marketing Moguls",
    "Newton’s Law",
    "Operation Optimizers",
    "Productivity Partners",
    "Project Pioneers",
    "Quality Quest",
    "Sales Superstars",
    "Strategic Thinkers",
    "Success Squad",
    "Synergy Slayers",
    "Synergy Specialists",
    "Synergy Squad",
    "Synergy Superheroes",
    "Synergy Superstars",
    "Tech Titans",
    "Tech Turtles",
    "Techie Tribe",
    "Techie Turtles",
    "The A Team",
    "The Brainy Bunch",
    "The Capitalists",
    "The Consultants",
    "The Entrepreneurs",
    "The Firm",
    "The Fixers",
    "The Mavericks",
    "The Moguls",
    "The Optimizers",
    "The Think Tank",
    "The Titans",
    "The Tycoons",
    "The Untouchables",
    "The Wizards of Odds",
    "The Wolfpack",
    "The Young and the Restless",
    "Think Tank",
    "Unlimited",
    "Win Machines",
    "Wonderful Wizards",
    "Workaholics",
    "World Domination Strategists",
    "World Wide Webmasters",
    "Xpressive Advertisers",
    "Zero Gravity"
]

adjectives = ["Dynamic", "Agile", "Innovative", "Strategic", "Synergistic", "Powerful", "Determined", "Fearless", "Creative", "Relentless"]

nouns = ["Eagles", "Pioneers", "Wizards", "Navigators", "Titans", "Lions", "Warriors", "Knights", "Gladiators", "Vikings"]

team_name = choice(adjectives) + " " + choice(nouns)


def nextTeamName():
    global teamNames
    if len(teamNames):
        return teamNames.pop(randint(0, len(teamNames) - 1))
    else:
        return choice(adjectives) + " " + choice(nouns)


project_names_descriptions = [
    ("Market Expansion Strategy", "Developing a comprehensive plan for expanding into new markets."),
    ("Digital Transformation", "Implementing digital solutions to improve efficiency."),
    ("Brand Revitalization", "Refreshing the brand to appeal to a new customer base."),
    ("Product Launch", "Launching a new product line."),
    ("Customer Experience", "Improving the customer experience."),
    ("Customer Retention", "Developing a strategy to increase customer retention."),
    ("Customer Acquisition", "Developing a strategy to increase customer acquisition."),
    ("Customer Loyalty", "Developing a strategy to increase customer loyalty."),
    ("Customer Satisfaction", "Developing a strategy to increase customer satisfaction."),
    ("Customer Engagement", "Developing a strategy to increase customer engagement."),
    ("Customer Support", "Developing a strategy to improve customer support."),
    ("Customer Service", "Developing a strategy to improve customer service."),
    ("Customer Success", "Developing a strategy to improve customer success."),
    ("Employee Engagement", "Developing a strategy to increase employee engagement."),
    ("Employee Satisfaction", "Developing a strategy to increase employee satisfaction."),
    ("Employee Retention", "Developing a strategy to increase employee retention."),
    ("Employee Loyalty", "Developing a strategy to increase employee loyalty."),
    ("Employee Experience", "Developing a strategy to improve employee experience."),
    ("Employee Support", "Developing a strategy to improve employee support."),
    ("Employee Service", "Developing a strategy to improve employee service."),
    ("Employee Success", "Developing a strategy to improve employee success."),
    ("Employee Happiness", "Developing a strategy to improve employee happiness."),
    ("Employee Morale", "Developing a strategy to improve employee morale."),
    ("Employee Wellness", "Developing a strategy to improve employee wellness."),
    ("Employee Health", "Developing a strategy to improve employee health."),
    ("Employee Safety", "Developing a strategy to improve employee safety."),
    ("Employee Productivity", "Developing a strategy to improve employee productivity."),
    ("Employee Efficiency", "Developing a strategy to improve employee efficiency."),
    ("Employee Performance", "Developing a strategy to improve employee performance."),
    ("Employee Effectiveness", "Developing a strategy to improve employee effectiveness."),
    ("Employee Development", "Developing a strategy to improve employee development."),
    ("Employee Training", "Developing a strategy to improve employee training."),
    ("Employee Education", "Developing a strategy to improve employee education."),
    ("Employee Growth", "Developing a strategy to improve employee growth."),
    ("Employee Advancement", "Developing a strategy to improve employee advancement."),
    ("Employee Promotion", "Developing a strategy to improve employee promotion."),
    ("Employee Recognition", "Developing a strategy to improve employee recognition."),
    ("Employee Compensation", "Developing a strategy to improve employee compensation."),
    ("Employee Benefits", "Developing a strategy to improve employee benefits."),
    ("Employee Perks", "Developing a strategy to improve employee perks."),
    ("Employee Rewards", "Developing a strategy to improve employee rewards."),
    ("Employee Incentives", "Developing a strategy to improve employee incentives."),
    ("Employee Motivation", "Developing a strategy to improve employee motivation."),
    ("Employee Engagement", "Developing a strategy to improve employee engagement."),
    ("Employee Collaboration", "Developing a strategy to improve employee collaboration."),
    ("Employee Communication", "Developing a strategy to improve employee communication."),
    ("Employee Feedback", "Developing a strategy to improve employee feedback."),
    ("Employee Input", "Developing a strategy to improve employee input."),
    ("Employee Ideas", "Developing a strategy to improve employee ideas."),
    ("Employee Suggestions", "Developing a strategy to improve employee suggestions."),
    ("Employee Participation", "Developing a strategy to improve employee participation."),
    ("Employee Involvement", "Developing a strategy to improve employee involvement."),
    ("Employee Empowerment", "Developing a strategy to improve employee empowerment."),
    ("Employee Ownership", "Developing a strategy to improve employee ownership."),
    ("Employee Accountability", "Developing a strategy to improve employee accountability."),
    ("Employee Responsibility", "Developing a strategy to improve employee responsibility."),
    ("Employee Morale", "Developing a strategy to improve employee morale."),
]


def nextProjectNameDescription():
    global project_names_descriptions
    if len(project_names_descriptions):
        return project_names_descriptions.pop(randint(0, len(project_names_descriptions) - 1))
    else:
        return ("Project " + str(randint(100, 999)), "Description " + str(randint(100, 999)))

section_names = [
    "Initial Planning",
    "Planning",
    "Research",
    "Research and Development",
    "Design",
    "Development",
    "Design Phase",
    "Development Phase",
    "Testing Phase",
    "Deployment Phase",
    "Post-Deployment Review",
    "Implementation",
    "Testing and Quality Assurance",
    "Deployment",
    "Post-Deployment Review",
    "Customer Support",
    "Customer Service",
    "Customer Success",
    "Marketing and Outreach",
    "Sales",
    "Customer Feedback",
    "Future Enhancements",
    "Future Development",
    "Future Improvements",
    "Future Features",
    # ... more names ...
]

def nextSectionName():
    global section_names
    if len(section_names):
        return section_names.pop(randint(0, len(section_names) - 1))
    else:
        return "Section " + str(randint(100, 999))



task_names_descriptions = [
    ("Develop Marketing Strategy", "Outline key marketing initiatives and channels for the upcoming year."),
    ("Develop Sales Strategy", "Outline key sales initiatives and channels for the upcoming year."),
    ("Develop Customer Success Strategy", "Outline key customer success initiatives and channels for the upcoming year."),
    ("Develop Customer Support Strategy", "Outline key customer support initiatives and channels for the upcoming year."),
    ("Develop Customer Service Strategy", "Outline key customer service initiatives and channels for the upcoming year."),
    ("Develop Customer Engagement Strategy", "Outline key customer engagement initiatives and channels for the upcoming year."),
    ("Develop Customer Loyalty Strategy", "Outline key customer loyalty initiatives and channels for the upcoming year."),
    ("Develop Customer Retention Strategy", "Outline key customer retention initiatives and channels for the upcoming year."),
    ("Develop Customer Acquisition Strategy", "Outline key customer acquisition initiatives and channels for the upcoming year."),
    ("Develop Customer Satisfaction Strategy", "Outline key customer satisfaction initiatives and channels for the upcoming year."),
    ("Develop Employee Engagement Strategy", "Outline key employee engagement initiatives and channels for the upcoming year."),
    ("Develop Employee Satisfaction Strategy", "Outline key employee satisfaction initiatives and channels for the upcoming year."),
    ("Develop Employee Retention Strategy", "Outline key employee retention initiatives and channels for the upcoming year."),
    ("Develop Employee Loyalty Strategy", "Outline key employee loyalty initiatives and channels for the upcoming year."),
    ("Develop Employee Experience Strategy", "Outline key employee experience initiatives and channels for the upcoming year."),
    ("Develop Employee Support Strategy", "Outline key employee support initiatives and channels for the upcoming year."),
    ("Develop Employee Service Strategy", "Outline key employee service initiatives and channels for the upcoming year."),
    ("Develop Employee Success Strategy", "Outline key employee success initiatives and channels for the upcoming year."),
    ("Develop Employee Happiness Strategy", "Outline key employee happiness initiatives and channels for the upcoming year."),
    ("Develop Employee Morale Strategy", "Outline key employee morale initiatives and channels for the upcoming year."),
    ("Develop Employee Wellness Strategy", "Outline key employee wellness initiatives and channels for the upcoming year."),
    ("Develop Employee Health Strategy", "Outline key employee health initiatives and channels for the upcoming year."),
    ("Develop Employee Safety Strategy", "Outline key employee safety initiatives and channels for the upcoming year."),
    ("Develop Employee Productivity Strategy", "Outline key employee productivity initiatives and channels for the upcoming year."),
    ("Develop Employee Efficiency Strategy", "Outline key employee efficiency initiatives and channels for the upcoming year."),
    ("Develop Employee Performance Strategy", "Outline key employee performance initiatives and channels for the upcoming year."),
    ("Develop Employee Effectiveness Strategy", "Outline key employee effectiveness initiatives and channels for the upcoming year."),
    ("Develop Employee Development Strategy", "Outline key employee development initiatives and channels for the upcoming year."),
    ("Develop Employee Training Strategy", "Outline key employee training initiatives and channels for the upcoming year."),
    ("Develop Employee Education Strategy", "Outline key employee education initiatives and channels for the upcoming year."),
    ("Develop Employee Growth Strategy", "Outline key employee growth initiatives and channels for the upcoming year."),
    ("Develop Employee Advancement Strategy", "Outline key employee advancement initiatives and channels for the upcoming year."),
    ("Develop Employee Promotion Strategy", "Outline key employee promotion initiatives and channels for the upcoming year."),
    ("Develop Employee Recognition Strategy", "Outline key employee recognition initiatives and channels for the upcoming year."),
    ("Develop Employee Compensation Strategy", "Outline key employee compensation initiatives and channels for the upcoming year."),
    ("Develop Employee Benefits Strategy", "Outline key employee benefits initiatives and channels for the upcoming year."),
    ("Develop Employee Perks Strategy", "Outline key employee perks initiatives and channels for the upcoming year."),
    ("Develop Employee Rewards Strategy", "Outline key employee rewards initiatives and channels for the upcoming year."),
    ("Develop Employee Incentives Strategy", "Outline key employee incentives initiatives and channels for the upcoming year."),
    ("Develop Employee Motivation Strategy", "Outline key employee motivation initiatives and channels for the upcoming year."),
    ("Develop Employee Engagement Strategy", "Outline key employee engagement initiatives and channels for the upcoming year."),
    ("Develop Employee Collaboration Strategy", "Outline key employee collaboration initiatives and channels for the upcoming year."),
    ("Develop Employee Communication Strategy", "Outline key employee communication initiatives and channels for the upcoming year."),
    ("Develop Employee Feedback Strategy", "Outline key employee feedback initiatives and channels for the upcoming year."),
    ("Develop Employee Input Strategy", "Outline key employee input initiatives and channels for the upcoming year."),
    ("Develop Employee Ideas Strategy", "Outline key employee ideas initiatives and channels for the upcoming year."),
    ("Develop Employee Suggestions Strategy", "Outline key employee suggestions initiatives and channels for the upcoming year."),
    ("Develop Employee Participation Strategy", "Outline key employee participation initiatives and channels for the upcoming year."),
    ("Develop Employee Involvement Strategy", "Outline key employee involvement initiatives and channels for the upcoming year."),
    ("Develop Employee Empowerment Strategy", "Outline key employee empowerment initiatives and channels for the upcoming year."),
    ("Develop Employee Ownership Strategy", "Outline key employee ownership initiatives and channels for the upcoming year."),
    ("Develop Employee Accountability Strategy", "Outline key employee accountability initiatives and channels for the upcoming year."),
    ("Develop Employee Responsibility Strategy", "Outline key employee responsibility initiatives and channels for the upcoming year."),
    ("Develop Employee Morale Strategy", "Outline key employee morale initiatives and channels for the upcoming year."),
    ("Develop Employee Morale Strategy", "Outline key employee morale initiatives and channels for the upcoming year."),
     ("Customer Feedback Analysis", "Analyze recent customer feedback to identify areas for improvement."),
    ("Competitor Research", "Research competitors' products and strategies for market comparison."),
    ("Budget Review", "Conduct a thorough review of the current budget and identify cost-saving opportunities."),
    ("Financial Forecasting", "Create a financial forecast for the next quarter based on current performance."),
    ("Financial Audit", "Conduct an audit of the company's financial records for the previous quarter."),
    ("Financial Planning", "Develop a financial plan for the next quarter based on current performance."),
    ("Financial Analysis", "Analyze the company's financial performance for the previous quarter."),
    ("Financial Reporting", "Prepare a financial report for the previous quarter."),
    ("Financial Modeling", "Develop a financial model for the next quarter based on current performance."),
    ("Financial Projections", "Create financial projections for the next quarter based on current performance."),
    ("Financial Statements", "Prepare financial statements for the previous quarter."),
    ("Website Redesign Plan", "Plan a complete redesign of the company website for a fresher look and better user experience."),
    ("Website Redesign", "Redesign the company website to improve user experience and increase conversions."),
    ("Website Maintenance", "Perform regular maintenance on the company website to ensure optimal performance."),
    ("Website Content Update", "Update the content on the company website to reflect recent changes."),
    ("Website Performance Analysis", "Analyze the performance of the company website to identify areas for improvement."),
    ("Website Traffic Analysis", "Analyze the traffic to the company website to identify areas for improvement."),
    ("Website Conversion Analysis", "Analyze the conversion rate of the company website to identify areas for improvement."),
    ("Website SEO Audit", "Conduct an SEO audit of the company website to identify areas for improvement."),
    ("Website SEO Optimization", "Optimize the company website for search engines to increase organic traffic."),
    ("Website SEO Strategy", "Develop an SEO strategy for the company website to increase organic traffic."),
    ("Website SEO Plan", "Develop an SEO plan for the company website to increase organic traffic."),
    ("Social Media Marketing Plan", "Develop a social media marketing plan to increase brand awareness and engagement."),
    ("Social Media Marketing Strategy", "Develop a social media marketing strategy to increase brand awareness and engagement."),
    ("Social Media Marketing Campaign", "Develop a social media marketing campaign to increase brand awareness and engagement."),
    ("Social Media Marketing Content", "Develop social media marketing content to increase brand awareness and engagement."),
    ("Social Media Marketing Calendar", "Develop a social media marketing calendar to increase brand awareness and engagement."),
    ("Social Media Marketing Analytics", "Analyze the performance of social media marketing campaigns to identify areas for improvement."),
    ("Social Media Marketing ROI", "Analyze the ROI of social media marketing campaigns to identify areas for improvement."),
    ("Sales Forecasting", "Create sales forecasts for the next quarter based on market trends and past performance."),
    ("Sales Analysis", "Analyze the company's sales performance for the previous quarter."),
    ("Sales Reporting", "Prepare a sales report for the previous quarter."),
    ("Sales Projections", "Create sales projections for the next quarter based on market trends and past performance."),
    ("Sales Pipeline Audit", "Conduct an audit of the company's sales pipeline to identify areas for improvement."),
    ("Sales Pipeline Analysis", "Analyze the company's sales pipeline to identify areas for improvement."),
    ("Sales Pipeline Optimization", "Optimize the company's sales pipeline to increase conversions."),
    ("Sales Pipeline Management", "Manage the company's sales pipeline to increase conversions."),
    ("Sales Pipeline Strategy", "Develop a sales pipeline strategy to increase conversions."),
    ("Sales Pipeline Plan", "Develop a sales pipeline plan to increase conversions."),
    ("Sales Pipeline Process", "Develop a sales pipeline process to increase conversions."),
    ("Sales Pipeline Standards", "Develop sales pipeline standards to increase conversions."),
    ("Sales Pipeline Guidelines", "Develop sales pipeline guidelines to increase conversions."),
    ("Sales Pipeline Training", "Train employees on sales pipeline best practices."),
    ("Sales Pipeline Awareness", "Increase employee awareness of sales pipeline best practices."),
    ("Sales Pipeline Education", "Educate employees on sales pipeline best practices."),
    ("Sales Pipeline Testing", "Test the company's sales pipeline to identify areas for improvement."),
    ("Sales Pipeline Assessment", "Assess the company's sales pipeline to identify areas for improvement."),
    ("Product Feature Enhancement", "Enhance product features based on customer feedback and usage data."),
    ("Product Feature Development", "Develop new product features based on customer feedback and usage data."),
    ("Product Feature Testing", "Test new product features based on customer feedback and usage data."),
    ("Product Feature Launch", "Launch new product features based on customer feedback and usage data."),
    ("Product Feature Marketing", "Develop a marketing strategy for new product features based on customer feedback and usage data."),
    ("Product Feature Sales", "Develop a sales strategy for new product features based on customer feedback and usage data."),
    ("Product Feature Pricing", "Develop a pricing strategy for new product features based on customer feedback and usage data."),
    ("Product Feature Packaging", "Develop a packaging strategy for new product features based on customer feedback and usage data."),
    ("Product Feature Distribution", "Develop a distribution strategy for new product features based on customer feedback and usage data."),
    ("Product Feature Advertising", "Develop an advertising strategy for new product features based on customer feedback and usage data."),
    ("Product Feature Promotion", "Develop a promotion strategy for new product features based on customer feedback and usage data."),
    ("Product Feature Branding", "Develop a branding strategy for new product features based on customer feedback and usage data."),
    ("Product Feature Positioning", "Develop a positioning strategy for new product features based on customer feedback and usage data."),
    ("Product Feature Messaging", "Develop a messaging strategy for new product features based on customer feedback and usage data."),
    ("Product Feature Targeting", "Develop a targeting strategy for new product features based on customer feedback and usage data."),
    ("Product Feature Segmentation", "Develop a segmentation strategy for new product features based on customer feedback and usage data."),
    ("Product Feature Market Research", "Conduct market research to identify potential ideas for new product features."),
    ("Product Feature Market Analysis", "Analyze the market to identify potential ideas for new product features."),
    ("Product Feature Market Reporting", "Prepare a report on the market to identify potential ideas for new product features."),
    ("Product Feature Market Plan", "Develop a plan for the market to identify potential ideas for new product features."),
    ("Product Feature Market Strategy", "Develop a strategy for the market to identify potential ideas for new product features."),
    ("Product Feature Market Process", "Develop a process for the market to identify potential ideas for new product features."),
    ("Product Feature Market Standards", "Develop standards for the market to identify potential ideas for new product features."),
    ("Product Feature Market Guidelines", "Develop guidelines for the market to identify potential ideas for new product features."),
    ("Product Feature Market Training", "Train employees on the market to identify potential ideas for new product features."),
    ("Product Feature Market Awareness", "Increase employee awareness of the market to identify potential ideas for new product features."),
    ("Product Feature Market Education", "Educate employees on the market to identify potential ideas for new product features."),
    ("Product Feature Market Testing", "Test the market to identify potential ideas for new product features."),
    ("Product Feature Market Assessment", "Assess the market to identify potential ideas for new product features."),
    ("Product Feature Market Management", "Manage the market to identify potential ideas for new product features."),
    ("Product Feature Market Remediation", "Remediate the market to identify potential ideas for new product features."),
    ("Employee Training Session", "Organize a training session for employees on the new software tool."),
    ("Data Migration Plan", "Plan the migration of data from legacy systems to the new platform."),
    ("Data Migration Strategy", "Develop a strategy for the migration of data from legacy systems to the new platform."),
    ("Data Migration Process", "Develop a process for the migration of data from legacy systems to the new platform."),
    ("Data Migration Testing", "Test the migration of data from legacy systems to the new platform."),
    ("Data Migration Assessment", "Assess the migration of data from legacy systems to the new platform."),
    ("Data Migration Management", "Manage the migration of data from legacy systems to the new platform."),
    ("Data Migration Remediation", "Remediate the migration of data from legacy systems to the new platform."),
    ("Data Migration Reporting", "Prepare a report on the migration of data from legacy systems to the new platform."),
    ("Supply Chain Optimization", "Analyze and optimize the supply chain process to reduce costs."),
    ("Supply Chain Management", "Manage the supply chain process to reduce costs."),
    ("Supply Chain Strategy", "Develop a supply chain strategy to reduce costs."),
    ("Supply Chain Plan", "Develop a supply chain plan to reduce costs."),
    ("Supply Chain Process", "Develop a supply chain process to reduce costs."),
    ("Supply Chain Audit", "Conduct an audit of the supply chain process to identify areas for improvement."),
    ("Supply Chain Analysis", "Analyze the supply chain process to identify areas for improvement."),
    ("Supply Chain Reporting", "Prepare a report on the supply chain process to identify areas for improvement."),
    ("Branding Campaign", "Develop a new branding campaign to increase brand awareness and presence."),
    ("Branding Strategy", "Develop a new branding strategy to increase brand awareness and presence."),
    ("Branding Plan", "Develop a new branding plan to increase brand awareness and presence."),
    ("Branding Audit", "Conduct an audit of the company's branding to identify areas for improvement."),
    ("Branding Analysis", "Analyze the company's branding to identify areas for improvement."),
    ("Branding Reporting", "Prepare a report on the company's branding to identify areas for improvement."),
    ("Branding Guidelines", "Develop branding guidelines to ensure consistency across all channels."),
    ("Branding Standards", "Develop branding standards to ensure consistency across all channels."),
    ("Branding Style Guide", "Develop a style guide to ensure consistency across all channels."),
    ("Branding Training", "Train employees on branding best practices."),
    ("Branding Awareness", "Increase employee awareness of branding best practices."),
    ("Branding Education", "Educate employees on branding best practices."),
    ("Branding Testing", "Test the company's branding to identify areas for improvement."),
    ("Branding Assessment", "Assess the company's branding to identify areas for improvement."),
    ("Branding Management", "Manage the company's branding to identify areas for improvement."),
    ("Branding Remediation", "Remediate the company's branding to identify areas for improvement."),
    ("Product Launch Plan", "Develop a plan for the launch of the new product."),
    ("Product Launch Strategy", "Develop a strategy for the launch of the new product."),
    ("Product Launch Process", "Develop a process for the launch of the new product."),
    ("Product Launch Standards", "Develop standards for the launch of the new product."),
    ("Product Launch Guidelines", "Develop guidelines for the launch of the new product."),
    ("Product Launch Training", "Train employees on the launch of the new product."),
    ("Product Launch Awareness", "Increase employee awareness of the launch of the new product."),
    ("Product Launch Education", "Educate employees on the launch of the new product."),
    ("Product Launch Testing", "Test the launch of the new product."),
    ("Product Launch Assessment", "Assess the launch of the new product."),
    ("Product Launch Management", "Manage the launch of the new product."),
    ("Product Launch Remediation", "Remediate the launch of the new product."),
    ("Product Launch Reporting", "Prepare a report on the launch of the new product."),
    ("New Product Research", "Conduct research to identify potential ideas for new product development."),
    ("New Product Development", "Develop a new product based on customer feedback and market research."),
    ("New Product Testing", "Test the new product to identify areas for improvement."),
    ("New Product Launch", "Launch the new product to the market."),
    ("New Product Marketing", "Develop a marketing strategy for the new product."),
    ("New Product Sales", "Develop a sales strategy for the new product."),
    ("New Product Pricing", "Develop a pricing strategy for the new product."),
    ("New Product Packaging", "Develop a packaging strategy for the new product."),
    ("New Product Distribution", "Develop a distribution strategy for the new product."),
    ("New Product Advertising", "Develop an advertising strategy for the new product."),
    ("New Product Promotion", "Develop a promotion strategy for the new product."),
    ("New Product Branding", "Develop a branding strategy for the new product."),
    ("New Product Positioning", "Develop a positioning strategy for the new product."),
    ("New Product Messaging", "Develop a messaging strategy for the new product."),
    ("New Product Targeting", "Develop a targeting strategy for the new product."),
    ("New Product Segmentation", "Develop a segmentation strategy for the new product."),
    ("New Product Market Research", "Conduct market research to identify potential ideas for new product development."),
    ("New Product Market Analysis", "Analyze the market to identify potential ideas for new product development."),
    ("New Product Market Reporting", "Prepare a report on the market to identify potential ideas for new product development."),
    ("New Product Market Plan", "Develop a plan for the market to identify potential ideas for new product development."),
    ("New Product Market Strategy", "Develop a strategy for the market to identify potential ideas for new product development."),
    ("New Product Market Process", "Develop a process for the market to identify potential ideas for new product development."),
    ("New Product Market Standards", "Develop standards for the market to identify potential ideas for new product development."),
    ("New Product Market Guidelines", "Develop guidelines for the market to identify potential ideas for new product development."),
    ("New Product Market Training", "Train employees on the market to identify potential ideas for new product development."),
    ("New Product Market Awareness", "Increase employee awareness of the market to identify potential ideas for new product development."),
    ("New Product Market Education", "Educate employees on the market to identify potential ideas for new product development."),
    ("New Product Market Testing", "Test the market to identify potential ideas for new product development."),
    ("New Product Market Assessment", "Assess the market to identify potential ideas for new product development."),
    ("New Product Market Management", "Manage the market to identify potential ideas for new product development."),
    ("New Product Market Remediation", "Remediate the market to identify potential ideas for new product development."),
    ("New Product Market Reporting", "Prepare a report on the market to identify potential ideas for new product development."),
    ("New Product Market Plan", "Develop a plan for the market to identify potential ideas for new product development."),
    ("New Product Market Strategy", "Develop a strategy for the market to identify potential ideas for new product development."),
    ("New Product Market Process", "Develop a process for the market to identify potential ideas for new product development."),
    ("New Product Market Standards", "Develop standards for the market to identify potential ideas for new product development."),
    ("New Product Market Guidelines", "Develop guidelines for the market to identify potential ideas for new product development."),
    ("New Product Market Training", "Train employees on the market to identify potential ideas for new product development."),
    ("New Product Market Awareness", "Increase employee awareness of the market to identify potential ideas for new product development."),
    ("New Product Market Education", "Educate employees on the market to identify potential ideas for new product development."),
    ("New Product Market Testing", "Test the market to identify potential ideas for new product development."),
    ("New Product Market Assessment", "Assess the market to identify potential ideas for new product development."),
    ("Social Media Strategy", "Develop a comprehensive social media strategy to increase engagement."),
    ("Social Media Plan", "Develop a comprehensive social media plan to increase engagement."),
    ("Social Media Campaign", "Develop a comprehensive social media campaign to increase engagement."),
    ("Social Media Content", "Develop a comprehensive social media content to increase engagement."),
    ("Social Media Calendar", "Develop a comprehensive social media calendar to increase engagement."),
    ("Social Media Analytics", "Analyze the performance of social media campaigns to identify areas for improvement."),
    ("Social Media ROI", "Analyze the ROI of social media campaigns to identify areas for improvement."),
    ("Social Media Audit", "Conduct an audit of the company's social media to identify areas for improvement."),
    ("Social Media Analysis", "Analyze the company's social media to identify areas for improvement."),
    ("Social Media Reporting", "Prepare a report on the company's social media to identify areas for improvement."),
    ("Social Media Guidelines", "Develop social media guidelines to ensure consistency across all channels."),
    ("Social Media Standards", "Develop social media standards to ensure consistency across all channels."),
    ("Social Media Style Guide", "Develop a style guide to ensure consistency across all channels."),
    ("Social Media Training", "Train employees on social media best practices."),
    ("Social Media Awareness", "Increase employee awareness of social media best practices."),
    ("Social Media Education", "Educate employees on social media best practices."),
    ("Social Media Testing", "Test the company's social media to identify areas for improvement."),

    ("Cybersecurity Upgrade", "Plan and implement cybersecurity upgrades across the company infrastructure."),
    ("Cybersecurity Audit", "Conduct an audit of the company's cybersecurity to identify areas for improvement."),
    ("Cybersecurity Analysis", "Analyze the company's cybersecurity to identify areas for improvement."),
    ("Cybersecurity Reporting", "Prepare a report on the company's cybersecurity to identify areas for improvement."),
    ("Cybersecurity Plan", "Develop a plan to improve the company's cybersecurity."),
    ("Cybersecurity Strategy", "Develop a strategy to improve the company's cybersecurity."),
    ("Cybersecurity Process", "Develop a process to improve the company's cybersecurity."),
    ("Cybersecurity Standards", "Develop standards to improve the company's cybersecurity."),
    ("Cybersecurity Guidelines", "Develop guidelines to improve the company's cybersecurity."),
    ("Cybersecurity Training", "Train employees on cybersecurity best practices."),
    ("Cybersecurity Awareness", "Increase employee awareness of cybersecurity best practices."),
    ("Cybersecurity Education", "Educate employees on cybersecurity best practices."),
    ("Cybersecurity Testing", "Test the company's cybersecurity to identify vulnerabilities."),
    ("Cybersecurity Vulnerability Assessment", "Assess the company's cybersecurity to identify vulnerabilities."),
    ("Cybersecurity Vulnerability Management", "Manage the company's cybersecurity to identify vulnerabilities."),
    ("Cybersecurity Vulnerability Remediation", "Remediate the company's cybersecurity to identify vulnerabilities."),
    ("Cybersecurity Vulnerability Reporting", "Prepare a report on the company's cybersecurity to identify vulnerabilities."),
    ("Cybersecurity Vulnerability Plan", "Develop a plan to improve the company's cybersecurity to identify vulnerabilities."),
    ("Cybersecurity Vulnerability Strategy", "Develop a strategy to improve the company's cybersecurity to identify vulnerabilities."),
    ("Cybersecurity Vulnerability Process", "Develop a process to improve the company's cybersecurity to identify vulnerabilities."),
    ("Cybersecurity Vulnerability Standards", "Develop standards to improve the company's cybersecurity to identify vulnerabilities."),
    ("Cybersecurity Vulnerability Guidelines", "Develop guidelines to improve the company's cybersecurity to identify vulnerabilities."),
    ("Cybersecurity Vulnerability Training", "Train employees on cybersecurity best practices to identify vulnerabilities."),
    ("Cybersecurity Vulnerability Awareness", "Increase employee awareness of cybersecurity best practices to identify vulnerabilities."),
    ("Employee Satisfaction Survey", "Conduct a survey to gauge employee satisfaction and gather feedback."),
    ("Recruitment Plan", "Create a recruitment plan to fill key positions in the company."),
    ("Software Development Sprint", "Plan and execute a two-week development sprint for the new software feature."),
    ("Performance Metrics Analysis", "Analyze current performance metrics and set targets for the next period."),
    ("Client Onboarding Process", "Standardize the client onboarding process for consistency and efficiency."),
    ("Quarterly Tax Filing", "Prepare and file taxes for the latest quarter."),
    ("Health and Safety Audit", "Conduct a health and safety audit of the workplace."),
    ("Sustainability Initiative Plan", "Develop a plan for sustainability initiatives to reduce the company's carbon footprint."),
    ("Market Expansion Study", "Study potential markets for expansion and growth opportunities."),
    ("Contract Review", "Review and update contracts with suppliers and partners."),
    ("Mobile App Development", "Start the development phase for the new mobile application."),
    ("Customer Loyalty Program", "Design and implement a customer loyalty program."),
    ("Project Post-Mortem", "Conduct a post-mortem analysis of the recently completed project."),
    ("Team Building Activity", "Organize a team-building activity to improve team collaboration."),
    ("Inventory Management System", "Implement a new inventory management system for better stock control."),
    ("Training Material Update", "Update the training materials for the new software version."),
    ("Customer Support Training", "Train customer support staff on the new software tool."),
    ("Employee Performance Review", "Conduct a performance review of all employees."),
    ("Employee Compensation Review", "Review employee compensation and benefits."),
    ("Employee Performance Bonus", "Determine employee performance bonuses for the previous quarter."),
    ("Employee Promotion Review", "Review employee performance for promotion opportunities."),
    ("Employee Training Session", "Organize a training session for employees on the new software tool."),
    ("Employee Onboarding Process", "Standardize the employee onboarding process for consistency and efficiency."),
    ("Employee Offboarding Process", "Standardize the employee offboarding process for consistency and efficiency."),
    ("Employee Exit Interviews", "Conduct exit interviews with employees leaving the company."),
    ("Employee Performance Review", "Conduct a performance review of all employees."),
    ("Employee Compensation Review", "Review employee compensation and benefits."),
    ("Employee Performance Bonus", "Determine employee performance bonuses for the previous quarter."),
    ("Employee Promotion Review", "Review employee performance for promotion opportunities."),
    ("Employee Training Session", "Organize a training session for employees on the new software tool."),
    ("Employee Onboarding Process", "Standardize the employee onboarding process for consistency and efficiency."),
    ("Employee Offboarding Process", "Standardize the employee offboarding process for consistency and efficiency."),
    ("Employee Exit Interviews", "Conduct exit interviews with employees leaving the company."),
    ("Employee Performance Review", "Conduct a performance review of all employees."),
    ("Employee Compensation Review", "Review employee compensation and benefits."),
    ("Employee Performance Bonus", "Determine employee performance bonuses for the previous quarter."),
    ("Employee Promotion Review", "Review employee performance for promotion opportunities."),
    ("Employee Training Session", "Organize a training session for employees on the new software tool."),
    ("Employee Onboarding Process", "Standardize the employee onboarding process for consistency and efficiency."),
    ("Employee Offboarding Process", "Standardize the employee offboarding process for consistency and efficiency."),
    ("Employee Exit Interviews", "Conduct exit interviews with employees leaving the company."),
    ("Employee Performance Review", "Conduct a performance review of all employees."),
    ("Employee Compensation Review", "Review employee compensation and benefits."),
    ("Employee Performance Bonus", "Determine employee performance bonuses for the previous quarter."),
    ("Employee Promotion Review", "Review employee performance for promotion opportunities."),
    ("Employee Training Session", "Organize a training session"),
    ]

itask_names_descriptions = task_names_descriptions.copy()

def nextTaskNameDescription():
    global task_names_descriptions
    if len(task_names_descriptions) > 0:
        return task_names_descriptions.pop(randint(0, len(task_names_descriptions) - 1))
    else:
        return ("Task " + str(randint(100, 999)), "Description " + str(randint(100, 999)))

def nextITaskNameDescription():
    global itask_names_descriptions
    if len(itask_names_descriptions) > 0:
        return itask_names_descriptions.pop(randint(0, len(itask_names_descriptions) - 1))
    else:
        return ("Task " + str(randint(100, 999)), "Description " + str(randint(100, 999)))
